source 'https://github.com/jiaojiaozhe/XAbstractionLibrary-Specs'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'ComponentModuleA_Example' do
  pod 'ComponentModuleA', :path => '../'

  target 'ComponentModuleA_Tests' do
    inherit! :search_paths

    
  end
end
